### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by leighayanid** [roughike/BottomBar#19]
java.lang.NoSuchMethodError: android.widget.FrameLayout.<init>
                                                                                at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:86)
                                                                                at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:72)
                                                                                at com.roughike.bottombar.BottomBar.attach(BottomBar.java:131)
                                                                                at com.example.bottombar.sample.MainActivity.onCreate(MainActivity.java:17)
                                                                                at android.app.Activity.performCreate(Activity.java:4470)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:128)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:137)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:4517)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by roughike** [comment]
Could you be more specific? How are you using the BottomBar?

**Comment by leighayanid** [comment]
i was able to build the sample app and deploy it on my device with api 14. But when I open the app, it crashes and it throws NoSuchMethodError.

**Comment by roughike** [comment]
Noted. This is definitely happening. I'll fix it ASAP.

**Comment by roughike** [comment]
Fixed in library version 1.0.4.

Huge thanks for reporting!
