### ISSUE TITLE
Caused by: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by shuncaigao** [roughike/BottomBar#210]
Process: com.k.k, PID: 8758
java.lang.RuntimeException: Unable to start activity ComponentInfo{ com.k.k com.k.k.activity.MainActivity}: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2626)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2695)
at android.app.ActivityThread.access$800(ActivityThread.java:173)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5791)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
Caused by: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
at com.roughike.bottombar.BottomBar.initializeViews(BottomBar.java:892)
at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:1159)
at com.roughike.bottombar.BottomBar.setItemsFromMenu(BottomBar.java:333)
at com.k.k.activity.MainActivity.initBottomBar(MainActivity.java:42)
at com.k.k.activity.MainActivity.onCreate(MainActivity.java:32)
at android.app.Activity.performCreate(Activity.java:6103)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2579)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2695) 
at android.app.ActivityThread.access$800(ActivityThread.java:173) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552) 
at android.os.Handler.dispatchMessage(Handler.java:111) 
at android.os.Looper.loop(Looper.java:194) 
at android.app.ActivityThread.main(ActivityThread.java:5791) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)

**Comment by shuncaigao** [comment]
Process: com.k.k, PID: 8758
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{ com.k.k com.k.k.activity.MainActivity}: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2626)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2695)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:173)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5791)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
                                                                  Caused by: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
                                                                     at com.roughike.bottombar.BottomBar.initializeViews(BottomBar.java:892)
                                                                     at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:1159)
                                                                     at com.roughike.bottombar.BottomBar.setItemsFromMenu(BottomBar.java:333)
                                                                     at  com.k.k.activity.MainActivity.initBottomBar(MainActivity.java:42)
                                                                     at  com.k.k.activity.MainActivity.onCreate(MainActivity.java:32)
                                                                     at android.app.Activity.performCreate(Activity.java:6103)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2579)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2695) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:173) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                     at android.os.Looper.loop(Looper.java:194) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5791) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)

**Comment by Nolanus** [comment]
Please provide some more details about your setup (xml layout, how you setup the BottomBar).

**Comment by rasika1021** [comment]
how to add spinner in bottom when ever i am adding my app get crash
