### ISSUE TITLE
NullPointerException occurred when i did not set mapColor.

### ISSUE THREAD

**Issue by jinnybrain** [roughike/BottomBar#23]
ver1.0.5

i did not set "mapColorForTab()" method.

(mColorMap is null)
>  java.lang.NullPointerException
                                                                                         at com.roughike.bottombar.BottomBar.handleBackgroundColorChange(BottomBar.java:545)
                                                                                         at com.roughike.bottombar.BottomBar.selectTab(BottomBar.java:530)
                                                                                         at com.roughike.bottombar.BottomBar.onClick(BottomBar.java:366)
                                                                                         at android.view.View.performClick(View.java:4492)
                                                                                         at android.view.View$PerformClick.run(View.java:18647)
                                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:136)

thank you.

**Comment by roughike** [comment]
Update your library to the latest version which is 1.0.7. It is now fixed.
