### ISSUE TITLE
Didn't find class "com.roughike.bottombar.R$color"

### ISSUE THREAD

**Issue by avivcaspi** [roughike/BottomBar#251]
hello!
when I try to use BottomBar object it crashes my app and show me this error 

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/roughike/bottombar/R$color;
                                                                                   at com.roughike.bottombar.BottomBar.init(BottomBar.java:871)
                                                                                   at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:849)
                                                                                   at com.roughike.bottombar.BottomBar.attach(BottomBar.java:141)
                                                                                   at com.example.avivcaspasd.test2.MainActivity.onCreate(MainActivity.java:64)
                                                                                   at android.app.Activity.performCreate(Activity.java:6092)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5631)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.roughike.bottombar.R$color" on path: DexPathList[[dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-support-annotations-23.3.0_15a489a6b9954c7556427c31fb70e591ee30a904-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-internal_impl-23.3.0_dbf0150ee372aaf011b44b8a4b0c5b4607a6daf9-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.github.roughike-BottomBar-e7f15cfd58_814a8bb3c895d2de4ecea345bcf91f7184088c72-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.3.0_b94deb7b436985e02bb458c222ac4c9dcceb4540-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.android.support-support-v4-23.3.0_f4aa1d7a7604ee6a526264efaefaa597839c5ab5-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.2.1_c76010a84757a74f143beac4d48a398d42760661-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.android.support-design-23.2.1_e5494703d4a1cafd59ca767553925cca6132cdce-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.3.0_ee46616a49d5640f2ba4de5b008d82ee77561b0d-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.3.0_b52ffdc6990af6e7a4caec20bedeea4297d19e13-classes.dex", dex file "/data/data/com.example.avivcaspasd.test2/files/instant-run/dex/slice-android-support-v4_
` 

i have no idea what to do to make it work.

in my code i use only one line 
BottomBar mBottomBar = BottomBar.attach(this, savedInstanceState);

**Comment by Xstar97** [comment]
you probably didnt implement all of it...so let me ask a few questions & you answer them fully...

1. Can you show the entire activity that's using bottombar?

2. are you creating the bottombar tabs through a menu.xml or programmatically?

3. are you correctly setting the colors to all tabs?

4. are you using fragments?

5. please try number 1

**Comment by avivcaspi** [comment]
First of all thank you for answering,
I did manage to make it work, just needed to restart android studio, now
I`m having a bit problem when trying to hide it when scroll
because I have got ViewList inside one of my fragments and putting another
scroll View upon it, makes a bit problems so I`m trying to work around it.
Thanks any way!
btw really great work!

**Comment by Xstar97** [comment]
I am not developer of this library, but I am just one of the many good devs trying to help others fix their issues...so the solution to your problem is this:

// Instead of attach(), use attachShy():
mBottomBar = BottomBar.attachShy((CoordinatorLayout) findViewById(R.id.myCoordinator), 
    findViewById(R.id.myScrollingContent), savedInstanceState);

//layout
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/myCoordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/myScrollingContent"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        

    </android.support.v4.widget.NestedScrollView>

</android.support.design.widget.CoordinatorLayout>
