### ISSUE TITLE
Crashed when fast switch item

### ISSUE THREAD

**Issue by Gracker** [roughike/BottomBar#30]
17:58:20.335 8390-8390/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.bottombar.sample, PID: 8390
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
                                                     at com.example.bottombar.sample.SampleFragment.onCreateView(SampleFragment.java:50)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5477)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
03-18 17:58:20.335 2825-3406/? W/ActivityManager:   Force finishing activity 1 com.example.bottombar.sample/.MainActivity

**Comment by roughike** [comment]
What version are you using?

**Comment by Gracker** [comment]
Android 5.1 && Android M 
Flyme 5.1

**Comment by roughike** [comment]
I was able to reproduce. 

However, this crash is not because of the library. It was because the dynamical creation of the TextView in the sample app.

I just updated it and now it shouldn't crash.

**Comment by roughike** [comment]
[Here's the updated code for the SampleFragment.](https://github.com/roughike/BottomBar/blob/master/app/src/main/java/com/example/bottombar/sample/SampleFragment.java)

**Comment by alirezanazari** [comment]
i have same problem with this!
is problem from frame layout ? an i change to view pager this problem will solve?
