### ISSUE TITLE
NoSuchMethodError: android.view.View.generateViewId

### ISSUE THREAD

**Issue by Blankeer** [roughike/BottomBar#325]
> FATAL EXCEPTION: main
                                                                  java.lang.NoSuchMethodError: android.view.View.generateViewId
                                                                      at kale.ui.view.BottomTabGroup$PassThroughHierarchyChangeListener.onChildViewAdded(BottomTabGroup.java:279)
                                                                      at android.view.ViewGroup.onViewAdded(ViewGroup.java:3359)
                                                                      at android.view.ViewGroup.addViewInner(ViewGroup.java:3473)
                                                                      at android.view.ViewGroup.addView(ViewGroup.java:3298)

This error in android 4.1.9,api 16.
Thanks.

**Comment by xizzhu** [comment]
What's the `BottomTabGroup` class? Seems it's not part of the BottomBar lib?

**Comment by ericsuwardi90** [comment]
As far as i know, generateViewId only available on API level 17 and above, you can check on this link for reference 

http://stackoverflow.com/questions/6790623/programmatic-views-how-to-set-unique-ids

**Comment by Blankeer** [comment]
Sorry I was wrong,it's nothing to do with BottomBar lib,Thank you for your reply.Thanks.
