### ISSUE TITLE
NullPointerException when clicking on some tab (with badge)

### ISSUE THREAD

**Issue by weswes** [roughike/BottomBar#329]
Hello,

I've got an error when clicking on a tab with a badge:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
                                                                                at com.roughike.bottombar.BottomBar.handleClick(BottomBar.java:1067)
                                                                                at com.roughike.bottombar.BottomBar.access$000(BottomBar.java:57)
                                                                                at com.roughike.bottombar.BottomBar$1.onClick(BottomBar.java:701)
                                                                                at android.view.View.performClick(View.java:5198)
                                                                                at android.view.View$PerformClick.run(View.java:21147)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

It seems that v.getTag() is null:

```
private void handleClick(View v) {
        if (v.getTag().equals(TAG_BOTTOM_BAR_VIEW_INACTIVE)) {
            View oldTab = findViewWithTag(TAG_BOTTOM_BAR_VIEW_ACTIVE);

            unselectTab(oldTab, true);
            selectTab(v, true);

            shiftingMagic(oldTab, v, true);
        }
        updateSelectedTab(findItemPosition(v));
    }
```

What is the problem here ?

**Comment by daedamr** [comment]
+1

**Comment by weswes** [comment]
I resolved the problem: I was calling mBottomBar.makeBadgeForTabAt each time I wanted to change the value of the tab badge.
Now, I create the badge once and then call: 

`badge.setCount(x);`

It seems that when you call mBottomBar.makeBadgeForTabAt many times for the same tab it recreates it and then the view used for handleClick is not the good one.
