### ISSUE TITLE
NullpointerException on onClick, I am using 'useFixedMode'

### ISSUE THREAD

**Issue by umair13adil** [roughike/BottomBar#408]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
                                                                                           at com.roughike.bottombar.BottomBar.handleClick(BottomBar.java:1153)
                                                                                           at com.roughike.bottombar.BottomBar.access$000(BottomBar.java:57)
                                                                                           at com.roughike.bottombar.BottomBar$1.onClick(BottomBar.java:751)
                                                                                           at android.view.View.performClick(View.java:4766)
                                                                                           at android.view.View$PerformClick.run(View.java:19683)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5538)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by TurhanOz** [comment]
Same here

**Comment by TurhanOz** [comment]
The exception happens also without the fixedMode.

There seems to be a race condition.
When you try to makeBadgeForTabAt later in your code, the crash happens.
When you do it as in the sample (right after the BottomBar instance + listener), the crash does not occur...

My workaround : 
- initiating the BottomBarBadge the sooner
- only hiding/showing it when needed  (with updating count)

**Comment by umair13adil** [comment]
Yes, that was exactly the problem. I am now showing badge after it initializes, not crashing anymore.
