### ISSUE TITLE
selectTabAtPosition crashes app ?

### ISSUE THREAD

**Issue by samirmangroliya** [roughike/BottomBar#433]
bottomBar.selectTabAtPosition(2);

```
[ Error reporting crash
                                                                          java.lang.OutOfMemoryError: Failed to allocate a 36486736 byte allocation with 16777216 free bytes and 22MB until OOM
                                                                              at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                                              at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
                                                                              at java.lang.StringBuffer.append(StringBuffer.java:278)
                                                                              at java.io.StringWriter.write(StringWriter.java:123)
                                                                              at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:358)
                                                                              at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:303)
                                                                              at com.android.internal.util.FastPrintWriter.write(FastPrintWriter.java:625)
                                                                              at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:658)
                                                                              at java.io.PrintWriter.append(PrintWriter.java:691)
                                                                              at java.io.PrintWriter.append(PrintWriter.java:687)
                                                                              at java.io.Writer.append(Writer.java:198)
                                                                              at java.lang.Throwable.printStackTrace(Throwable.java:324)
                                                                              at java.lang.Throwable.printStackTrace(Throwable.java:300)
                                                                              at android.util.Log.getStackTraceString(Log.java:343)
                                                                              at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                              at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                              at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                              at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                              at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
08-24 04:47:42.437 26700-26700/com.zeustechnocrats.bhis I/Process: Sending signal. PID: 26700 SIG: 9](url)
```

**Comment by roughike** [comment]
I can't reproduce this issue. Could you provide some more code? What happens on your ```OnTabSelectListener()```?

**Comment by foxapp** [comment]
selectTabAtPosition() need to be before OnTabSelectListener()

**Comment by punyfeir** [comment]
add this bottomBar = (BottomBar) findViewById(R.id.bottomBar); before you call bottomBar.selectTabAtPosition(2);
