### ISSUE TITLE
2.0.2 is error in DataBinding

### ISSUE THREAD

**Issue by leo75090** [roughike/BottomBar#459]
It will be error in Android Studio DataBinding
binding = DataBindingUtil.setContentView(this,R.layout.activity_main);

logcat:
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at android.databinding.ViewDataBinding.mapBindings(ViewDataBinding.java:922)
at android.databinding.ViewDataBinding.mapBindings(ViewDataBinding.java:995)

**Comment by remydavid** [comment]
Same for me, I am forced to revert to 2.0.0 for now

**Comment by Chikrix** [comment]
Same for me

**Comment by salismt** [comment]
Same for me, but 2.0 has bug when u click between inactive and active tab, revert to 2.0.1

**Comment by zjuxxd** [comment]
Same problem. 2.0.1 works for me.

**Comment by tushar-acharya** [comment]
@roughike I've fix this in my PR and also updated all library versions - https://github.com/roughike/BottomBar/pull/528
