### ISSUE TITLE
 java.lang.NullPointerException in void com.roughike.bottombar.BottomBarTab.deselect(boolean)

### ISSUE THREAD

**Issue by r91andersson** [roughike/BottomBar#567]
The error occurs usally when I minimize the app for a longer period. Then when I reopen the app, it crashes. This is the error log I get:

java.lang.RuntimeException: Unable to start activity ComponentInfo{integrum.bioniclimbcontroller/integrum.bioniclimbcontroller.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.roughike.bottombar.BottomBarTab.deselect(boolean)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.roughike.bottombar.BottomBarTab.deselect(boolean)' on a null object reference
        at com.roughike.bottombar.BottomBar.selectTabAtPosition(BottomBar.java:706)
        at com.roughike.bottombar.BottomBar.restoreState(BottomBar.java:652)
        at com.roughike.bottombar.BottomBar.onRestoreInstanceState(BottomBar.java:638)
        at android.view.View.dispatchRestoreInstanceState(View.java:14839)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3122)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3128)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3128)
        at android.view.View.restoreHierarchyState(View.java:14817)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2042)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1013)
        at android.app.Activity.performRestoreInstanceState(Activity.java:968)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1164)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)

**Comment by r91andersson** [comment]
I have found the problem to be some issue with that the bundle are not loaded correctly when the application is reopened due to other applications taking up the memory. So my not so fancy solution to this was to sorround the following with try and catch block:
* oldTab.deselect(animate);
* newTab.select(animate);
* handleBackgroundColorChange(newTab, false);

This at least solved that the app didn't crash. However I think there should be some checking in the method "onRestoreInstanceState" and "restoreState" to verify that the bundle is correctly loaded. @roughike
