### ISSUE TITLE
Binary XML file line #51: Error inflating class com.roughike.bottombar.BottomBar on Pre Lolipop

### ISSUE THREAD

**Issue by andhikayuana** [roughike/BottomBar#581]
Hello, im Andhika from Indonesia, I want to ask about bottomBar
I get error this, when i run on android pre lolipop
<pre>
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: id.superpromo.shopper, PID: 2453
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{id.superpromo.shopper/id.superpromo.shopper.views.activities.MainActivity}: android.view.InflateException: Binary XML file line #51: Error inflating class com.roughike.bottombar.BottomBar
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #51: Error inflating class com.roughike.bottombar.BottomBar
                      at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at id.superpromo.shopper.views.BaseActivity.onCreate(BaseActivity.java:26)
                      at android.app.Activity.performCreate(Activity.java:5231)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at id.superpromo.shopper.views.BaseActivity.onCreate(BaseActivity.java:26) 
                      at android.app.Activity.performCreate(Activity.java:5231) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020093
                      at android.content.res.Resources.getValue(Resources.java:1123)
                      at android.support.v7.widget.ResourcesWrapper.getValue(ResourcesWrapper.java:204)
                      at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:321)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                      at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
                      at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
                      at com.roughike.bottombar.BottomBarTab.prepareLayout(BottomBarTab.java:103)
                      at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:273)
                      at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:239)
                      at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:222)
                      at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:110)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at id.superpromo.shopper.views.BaseActivity.onCreate(BaseActivity.java:26) 
                      at android.app.Activity.performCreate(Activity.java:5231) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
</pre>
how to solve this? i have check on this 
`<?xml version="1.0" encoding="utf-8"?>
<tabs>
    <tab
        id="@+id/tab_home"
        icon="@drawable/ic_home"
        title="@string/home" />
    <tab
        id="@+id/tab_favorite"
        icon="@drawable/ic_favorite"
        title="@string/favorite" />
    <tab
        id="@+id/tab_category"
        icon="@drawable/ic_category"
        title="@string/category" />
</tabs>`
the drawable is exist
or i must check another xml too ? thanks

**Comment by andhikayuana** [comment]
solved remove `vectorDrawables.useSupportLibrary = true` in gradle
