### ISSUE TITLE
java.lang.RuntimeException: No items specified for the BottomBar!

### ISSUE THREAD

**Issue by iman2420** [roughike/BottomBar#582]
By this code :

            <com.roughike.bottombar.BottomBar
            android:id="@+id/bottomBar"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:bb_tabletMode="true"
            app:bb_tabXmlResource="@xml/bottombar_tabs" />

I got this **error**:

>  Caused by: java.lang.RuntimeException: No items specified for the BottomBar!
                                                                        at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:231)
                                                                        at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:222)
                                                                        at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:110)

please help me...

**Comment by DiegoCatalano** [comment]
I got the same problem

**Comment by DiegoCatalano** [comment]
@iman2420 I fixed this.

Just put this line in your layout.

`xmlns:app="http://schemas.android.com/apk/res-auto"`
