### ISSUE TITLE
Error inflating class android.support.v7.widget.AppCompatImageView

### ISSUE THREAD

**Issue by iman2420** [roughike/BottomBar#611]
` FATAL EXCEPTION: main
                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iman.marashiquiz/com.special.MainActivity}: android.view.InflateException: Binary **XML file line #35: Error inflating class com.roughike.bottombar.BottomBar**
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                           at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                           at android.os.Looper.loop(Looper.java:137)
                                           at android.app.ActivityThread.main(ActivityThread.java:5041)
                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                           at dalvik.system.NativeStart.main(Native Method)
                                        Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class com.roughike.bottombar.BottomBar
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                           at com.special.RootLevelsFragment.onCreateView(RootLevelsFragment.java:40)
                                           at android.app.Fragment.performCreateView(Fragment.java:1695)
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
                                           at android.app.BackStackRecord.run(BackStackRecord.java:682)
                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
                                           at android.app.Activity.performStart(Activity.java:5113)
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                           at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                           at android.os.Looper.loop(Looper.java:137) 
                                           at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                           at dalvik.system.NativeStart.main(Native Method) 
                                        Caused by: java.lang.reflect.InvocationTargetException
                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                           at com.special.RootLevelsFragment.onCreateView(RootLevelsFragment.java:40) 
                                           at android.app.Fragment.performCreateView(Fragment.java:1695) 
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885) 
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057) 
                                           at android.app.BackStackRecord.run(BackStackRecord.java:682) 
                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435) 
                                           at android.app.Activity.performStart(Activity.java:5113) 
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                           at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                           at android.os.Looper.loop(Looper.java:137) 
                                           at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                           at dalvik.system.NativeStart.main(Native Method) 
                                        Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class android.support.v7.widget.AppCompatImageView
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                           at android.view.View.inflate(View.java:16465)
                                           at com.roughike.bottombar.BottomBarTab.prepareLayout(BottomBarTab.java:97)
                                           at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:273)
                                           at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:239)
                                           at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:222)
                                           at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:110)
                                           at java.lang.reflect.Constructor.constructNative(Native Method) 
                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                           at com.special.RootLevelsFragment.onCreateView(RootLevelsFragment.java:40) 
                                           at android.app.Fragment.performCreateView(Fragment.java:1695) 
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885) 
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057) 
                                           at android.app.BackStackRecord.run(BackStackRecord.java:682) 
                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435) 
                                           at android.app.Activity.performStart(Activity.java:5113) 
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                           at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                           at android.os.Looper.loop(Looper.java:137) 
                                           at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                           at dalvik.system.NativeStart.main(Native Method) 
                                        Caused by: java.lang.reflect.InvocationTargetException
                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                           at android.view.View.inflate(View.java:16465) 
                                           at com.roughike.bottombar.BottomBarTab.prepareLayout(BottomBarTab.java:97) 
                                           at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:273) 
                                           at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:239) 
                                           at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:222) 
                                           at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:110) 
                                           at java.lang.reflect.Constructor.constructNative(Native Method) 
                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                           at com.special.RootLevelsFragment.onCreateView(RootLevelsFragment.java:40) 
                                           at android.app.Fragment.performCreateView(Fragment.java:1695) 
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885) 
                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057) 
                                           at android.app.BackStackRecord.run(BackStackRecord.java:682) 
                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435) 
                                           at android.app.Activity.performStart(Activity.java:5113) 
                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                           at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                           at android.os.Looper.loop(Looper.java:137) 
                                           at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                           at dalvik.system.NativeStart.main(Native Method) 
                                        Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010064 a=2}
                                           at android.content.res.Resources.loadDrawable(Resources.java:1927)
                                           at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                           at android.view.View.<init>(View.java:3330)
                                           at android.widget.ImageView.<init>(ImageView.java:114)
                                           at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:57)
                                       	at android.support.v7.widget.AppCompatImageView.<init>

I got this error in **tablet** mode.

**Comment by leonardo2204** [comment]
What OS and lib versions are you using ?
