### ISSUE TITLE
java.lang.ArithmeticException: divide by zero error

### ISSUE THREAD

**Issue by BlaineOmega** [roughike/BottomBar#632]
I keep getting an java.lang.ArithmeticException: divide by zero error when I try to inflate the bottom bar. Here is the whole stacktrace:

```
01-21 17:21:31.025 10558-10558/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.blaine.streetartfinder, PID: 10558
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.blaine.streetartfinder/com.example.blaine.streetartfinder.MainActivity}: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class com.roughike.bottombar.BottomBar
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class com.roughike.bottombar.BottomBar
                                                    Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.roughike.bottombar.BottomBar
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                       at com.example.blaine.streetartfinder.MainActivity.onCreate(MainActivity.java:26)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.ArithmeticException: divide by zero
                                                       at com.roughike.bottombar.BottomBar.resizeTabsToCorrectSizes(BottomBar.java:322)
                                                       at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:310)
                                                       at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:246)
                                                       at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:229)
                                                       at com.roughike.bottombar.BottomBar.init(BottomBar.java:122)
                                                       at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:111)
                                                       at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                       at com.example.blaine.streetartfinder.MainActivity.onCreate(MainActivity.java:26) 
                                                       at android.app.Activity.performCreate(Activity.java:6679) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Arunkumar080** [comment]
I am also getting the same error during the designing a activity with BottomBar.

  Rendering Problems The following classes could not be instantiated:
- com.roughike.bottombar.BottomBar (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.ArithmeticException: / by zero   at com.roughike.bottombar.BottomBar.resizeTabsToCorrectSizes(BottomBar.java:322)

Complete stack is :
java.lang.ArithmeticException: / by zero
	at com.roughike.bottombar.BottomBar.resizeTabsToCorrectSizes(BottomBar.java:322)
	at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:310)
	at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:246)
	at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:229)
	at com.roughike.bottombar.BottomBar.init(BottomBar.java:122)
	at com.roughike.bottombar.BottomBar.<init>(BottomBar.java:111)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Lamba92** [comment]
Exact same error here... Building on latest android studio on win10, minSDK 18, max 25
