### ISSUE TITLE
BottomBar crashes the App: Null Pointer Exception, tried initializing with & without ButterKnife

### ISSUE THREAD

**Issue by talhahasanzia** [roughike/BottomBar#814]
The error:
```
 FATAL EXCEPTION: main
                                                                         Process: com.mujadidia.duaoazkar, PID: 26580
                                                                         java.lang.RuntimeException: Unable to resume activity {com.mujadidia.duaoazkar/com.mujadidia.duaoazkar.home.HomeView}: java.lang.NullPointerException
                                                                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2795)
                                                                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2824)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5105)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.NullPointerException
                                                                             at com.mujadidia.duaoazkar.home.HomeTab.Home.HomeTabView.hideDropDownList(HomeTabView.java:230)
                                                                             at com.mujadidia.duaoazkar.home.HomeTab.Home.HomeTabView.dropList(HomeTabView.java:146)
                                                                             at com.mujadidia.duaoazkar.home.HomeView.hideDropDown(HomeView.java:184)
                                                                             at com.mujadidia.duaoazkar.home.HomeView$1.onTabSelected(HomeView.java:106)
                                                                             at com.roughike.bottombar.BottomBar.setOnTabSelectListener(BottomBar.java:481)
                                                                             at com.roughike.bottombar.BottomBar.setOnTabSelectListener(BottomBar.java:465)
                                                                             at com.mujadidia.duaoazkar.home.HomeView.onResume(HomeView.java:95)
                                                                             at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
                                                                             at android.app.Activity.performResume(Activity.java:5354)
                                                                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2785)
                                                                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2824) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
```

The Activity code:
```

public BottomBar bottomBar;
	public ViewPager viewPager;
	
	
	@Override
	protected void onCreate( Bundle savedInstanceState )
	{
		super.onCreate( savedInstanceState );
		Fabric.with( this, new Crashlytics() );
		setContentView( R.layout.activity_home_view );
		
		ButterKnife.bind( this );
		
		viewPager= (ViewPager) findViewById( R.id.view_pager );
		bottomBar= (BottomBar) findViewById( R.id.bottomBar );
	}


	@Override
	protected void onResume()
	{
		super.onResume();
		
		
		viewPager.setAdapter( new HomeViewPager( getSupportFragmentManager() ) );
		
		
		bottomBar.setOnTabSelectListener( new OnTabSelectListener()
		{
			@Override
			public void onTabSelected( @IdRes int tabId )
			{
				switch ( tabId )
				{
					
					case R.id.tab_home:
						viewPager.setCurrentItem( 0 );
						
						hideDropDown();
						
						break;
					
					case R.id.tab_favorite:
						viewPager.setCurrentItem( 1 );
						break;
					
					case R.id.tab_search:
						viewPager.setCurrentItem( 2 );
						break;
					
					case R.id.tab_tasbeeh:
						viewPager.setCurrentItem( 3 );
						break;
					
					case R.id.tab_settings:
						viewPager.setCurrentItem( 4 );
						break;
					
					
				}
			}
		} );
		
		
		bottomBar.setOnTabReselectListener( new OnTabReselectListener()
		{
			@Override
			public void onTabReSelected( @IdRes int tabId )
			{
				if ( tabId == R.id.tab_home )
				{
					hideDropDown();
					
				}
			}
			
		} );
		
		
		viewPager.addOnPageChangeListener( new ViewPager.OnPageChangeListener()
		{
			@Override
			public void onPageScrolled( int position, float positionOffset, int positionOffsetPixels )
			{
				
			}
			
			@Override
			public void onPageSelected( int position )
			{
				bottomBar.selectTabAtPosition( position );
			}
			
			@Override
			public void onPageScrollStateChanged( int state )
			{
				
			}
		} );
		
		
	}
```

My gradle file:

```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}


android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.superapps.app"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '25.3.1'
                }
            }
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }

    compile 'com.karumi:dexter:4.1.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.skyfishjy.ripplebackground:library:1.0.1'
    compile 'com.google.dagger:dagger:2.9'
    compile 'com.facebook.android:facebook-android-sdk:4.24.0'
    compile 'com.jakewharton:butterknife:8.6.0'
    compile 'com.roughike:bottom-bar:2.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.github.florent37:viewanimator:1.0.5'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha8'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.firebase:firebase-ads:10.0.1'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.9'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
    provided 'javax.annotation:jsr250-api:1.0'
}


```apply plugin: 'com.google.gms.google-services'

**Comment by talhahasanzia** [comment]
Runs fine on Nexus 6, 6P and Samsung S6.
