### ISSUE TITLE
xml error?

### ISSUE THREAD

**Issue by raybest4u** [roughike/BottomBar#85]
java.lang.RuntimeException: Unable to start activity ComponentInfo{ main.MainActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                            Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                               at android.view.View.inflate(View.java:19784)
                                                               at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:760)
                                                               at com.roughike.bottombar.BottomBar.setItemsFromMenu(BottomBar.java:305)
                                                               at cn.thinkeye.ui.main.MainActivity.onCreate(MainActivity.java:33)
                                                               at android.app.Activity.performCreate(Activity.java:6237)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                            Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                               at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                               at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at android.view.View.inflate(View.java:19784) 
                                                               at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:760) 
                                                               at com.roughike.bottombar.BottomBar.setItemsFromMenu(BottomBar.java:305) 
                                                               at cn.thinkeye.ui.main.MainActivity.onCreate(MainActivity.java:33) 
                                                               at android.app.Activity.performCreate(Activity.java:6237) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                               at java.lang.reflect.Constructor.newInstance(Native Method)
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                               at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                               at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at android.view.View.inflate(View.java:19784) 
                                                               at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:760) 
                                                               at com.roughike.bottombar.BottomBar.setItemsFromMenu(BottomBar.java:305) 
                                                               at cn.thinkeye.ui.main.MainActivity.onCreate(MainActivity.java:33) 
                                                               at android.app.Activity.performCreate(Activity.java:6237) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                            Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f01005d a=2}
                                                               at android.content.res.TypedArray.getDrawable(TypedArray.java:867)
                                                               at android.view.View.<init>(View.java:3948)
                                                               at android.view.ViewGroup.<init>(ViewGroup.java:573)
                                                               at android.widget.LinearLayout.<init>(LinearLayout.java:203)
                                                               at android.widget.LinearLayout.<init>(LinearLayout.java:199)
                                                               at android.widget.LinearLayout.<init>(LinearLayout.java:195)
                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                               at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                               at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at android.view.View.inflate(View.java:19784) 
                                                               at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:760) 
                                                               at com.roughike.bottombar.BottomBar.setItemsFromMenu(BottomBar.java:305) 
                                                               at cn.thinkeye.ui.main.MainActivity.onCreate(MainActivity.java:33) 
                                                               at android.app.Activity.performCreate(Activity.java:6237) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by roughike** [comment]
Check if the drawables that you're using in your XML menu resource all exist.
